import type { AlbumGroup } from "@/types/album";

export const albums: AlbumGroup[] = [
  {
    id: "basico",
    title: "Curso Básico",
    description: "Fotos do período básico de formação.",
    icon: "basico",
    cover: "",
    items: [
      {
        id: "1-pelotao",
        name: "1º Pelotão",
        path: "basico/1-pelotao",
        description: "Fotos do 1º Pelotão.",
        cover: "",
        icon: "pelotao",
        photos: 0,
      },
      {
        id: "2-pelotao",
        name: "2º Pelotão",
        path: "basico/2-pelotao",
        description: "Fotos do 2º Pelotão.",
        cover: "",
        icon: "pelotao",
        photos: 0,
      },
      {
        id: "3-pelotao",
        name: "3º Pelotão",
        path: "basico/3-pelotao",
        description: "Fotos do 3º Pelotão.",
        cover: "",
        icon: "pelotao",
        photos: 0,
      },
      {
        id: "4-pelotao",
        name: "4º Pelotão",
        path: "basico/4-pelotao",
        description: "Fotos do 4º Pelotão.",
        cover: "",
        icon: "pelotao",
        photos: 0,
      },
      {
        id: "5-pelotao",
        name: "5º Pelotão",
        path: "basico/5-pelotao",
        description: "Fotos do 5º Pelotão.",
        cover: "",
        icon: "pelotao",
        photos: 0,
      },
      {
        id: "6-pelotao",
        name: "6º Pelotão",
        path: "basico/6-pelotao",
        description: "Fotos do 6º Pelotão.",
        cover: "",
        icon: "pelotao",
        photos: 0,
      },
    ],
  },

  {
    id: "aqs",
    title: "Armas, Quadros e Serviços",
    description: "Fotos das Armas, Quadros e Serviços.",
    icon: "armas",
    cover: "",
    items: [
      {
        id: "1-infantaria",
        name: "Infantaria",
        path: "armas-quadros-servicos/1-infantaria",
        description: "Fotos da Infantaria.",
        cover: "",
        icon: "album",
        photos: 0,
      },
      {
        id: "2-cavalaria",
        name: "Cavalaria",
        path: "armas-quadros-servicos/2-cavalaria",
        description: "Fotos da Cavalaria.",
        cover: "",
        icon: "album",
        photos: 0,
      },
      {
        id: "3-artilharia",
        name: "Artilharia",
        path: "armas-quadros-servicos/3-artilharia",
        description: "Fotos da Artilharia.",
        cover: "",
        icon: "album",
        photos: 0,
      },
      {
        id: "4-engenharia",
        name: "Engenharia",
        path: "armas-quadros-servicos/4-engenharia",
        description: "Fotos da Engenharia.",
        cover: "",
        icon: "album",
        photos: 0,
      },
      {
        id: "5-comunicacoes",
        name: "Comunicações",
        path: "armas-quadros-servicos/5-comunicacoes",
        description: "Fotos das Comunicações.",
        cover: "",
        icon: "album",
        photos: 0,
      },
      {
        id: "6-intendencia",
        name: "Intendência",
        path: "armas-quadros-servicos/6-intendencia",
        description: "Fotos da Intendência.",
        cover: "",
        icon: "album",
        photos: 0,
      },
      {
        id: "7-material-belico",
        name: "Material Bélico",
        path: "armas-quadros-servicos/7-material-belico",
        description: "Fotos do Material Bélico.",
        cover: "",
        icon: "album",
        photos: 0,
      },
    ],
  },

  {
    id: "reencontros",
    title: "Reencontros",
    description:
      "Fotografias dos reencontros da Turma Marechal Waldemar Levy Cardoso.",
    icon: "reencontros",
    cover: "",
    items: [
      {
        id: "2027",
        name: "Reencontro 2027",
        path: "reencontros/2027",
        description: "Primeiro reencontro oficial da turma.",
        cover: "",
        icon: "album",
        photos: 0,
      },
    ],
  },
];